id: P004131
initial_creation_type: ocr
source_metadata:
  id: bdr:W20074
  title: བསླབ་བྱ་ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    bbcc2a35c04243ddb78adc82e36b43cf:
      image_group_id: I4819
      title: ''
      volume_number: 1
      total_pages: 244
